2017-07-08 21:46:40 [27609] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  syslog: False
  statsd_host: ('localhost', 8125)
  post_fork: <function post_fork at 0x7fd8e5555a28>
  pythonpath: ./tweety
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7fd8e5555758>
  pre_fork: <function pre_fork at 0x7fd8e55558c0>
  cert_reqs: 0
  preload_app: False
  workers: 1
  keepalive: 2
  accesslog: None
  pidfile: None
  worker_tmp_dir: None
  group: 1000
  graceful_timeout: 30
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7fd8e55555f0>
  post_worker_init: <function post_worker_init at 0x7fd8e5555b90>
  pre_exec: <function pre_exec at 0x7fd8e5559050>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fd8e55596e0>
  config: None
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fd8e55591b8>
  post_request: <function post_request at 0x7fd8e55592a8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fd8e5555cf8>
  ca_certs: None
  threads: 1
  max_requests: 0
  chdir: /home/ank/projects/tweety-app/tweety
  daemon: False
  user: 1000
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fd8e5559410>
  paste: None
  default_proc_name: tweety:application
  errorlog: ./gunicorn_tweety.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7fd8e5555e60>
  loglevel: debug
  bind: ['0.0.0.0:5000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fd8e5559578>
  timeout: 30
  on_starting: <function on_starting at 0x7fd8e5555488>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
2017-07-08 21:46:40 [27609] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:46:40 [27609] [DEBUG] Arbiter booted
2017-07-08 21:46:40 [27609] [INFO] Listening at: http://0.0.0.0:5000 (27609)
2017-07-08 21:46:40 [27609] [INFO] Using worker: sync
2017-07-08 21:46:40 [27615] [INFO] Booting worker with pid: 27615
2017-07-08 21:46:40 [27609] [INFO] 1 workers
2017-07-08 21:46:40 [27615] [DEBUG] Exception while loading the application: 
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 369, in import_app
    raise AppImportError("Failed to find application: %r" % module)
AppImportError: Failed to find application: 'tweety'

2017-07-08 21:46:40 [27615] [INFO] Worker exiting (pid: 27615)
2017-07-08 21:46:40 [27609] [INFO] Shutting down: Master
2017-07-08 21:46:40 [27609] [INFO] Reason: App failed to load.
2017-07-08 21:49:51 [28069] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  syslog: False
  statsd_host: ('localhost', 8125)
  post_fork: <function post_fork at 0x7f44f9be0a28>
  pythonpath: ./tweety
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7f44f9be0758>
  pre_fork: <function pre_fork at 0x7f44f9be08c0>
  cert_reqs: 0
  preload_app: False
  workers: 1
  keepalive: 2
  accesslog: None
  pidfile: None
  worker_tmp_dir: None
  group: 1000
  graceful_timeout: 30
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7f44f9be05f0>
  post_worker_init: <function post_worker_init at 0x7f44f9be0b90>
  pre_exec: <function pre_exec at 0x7f44f9be4050>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f44f9be46e0>
  config: None
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f44f9be41b8>
  post_request: <function post_request at 0x7f44f9be42a8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f44f9be0cf8>
  ca_certs: None
  threads: 1
  max_requests: 0
  chdir: /home/ank/projects/tweety-app/tweety
  daemon: False
  user: 1000
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f44f9be4410>
  paste: None
  default_proc_name: tweety.wsgi:application
  errorlog: ./gunicorn_tweety.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7f44f9be0e60>
  loglevel: debug
  bind: ['0.0.0.0:5000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f44f9be4578>
  timeout: 30
  on_starting: <function on_starting at 0x7f44f9be0488>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
2017-07-08 21:49:51 [28069] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:49:51 [28069] [DEBUG] Arbiter booted
2017-07-08 21:49:51 [28069] [INFO] Listening at: http://0.0.0.0:5000 (28069)
2017-07-08 21:49:51 [28069] [INFO] Using worker: sync
2017-07-08 21:49:51 [28075] [INFO] Booting worker with pid: 28075
2017-07-08 21:49:51 [28069] [INFO] 1 workers
2017-07-08 21:49:52 [28075] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2017-07-08 21:49:52 [28075] [INFO] Worker exiting (pid: 28075)
2017-07-08 21:49:52 [28069] [INFO] Shutting down: Master
2017-07-08 21:49:52 [28069] [INFO] Reason: Worker failed to boot.
2017-07-08 21:50:32 [28161] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  syslog: False
  statsd_host: ('localhost', 8125)
  post_fork: <function post_fork at 0x7f595f848a28>
  pythonpath: ./tweety
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7f595f848758>
  pre_fork: <function pre_fork at 0x7f595f8488c0>
  cert_reqs: 0
  preload_app: False
  workers: 1
  keepalive: 2
  accesslog: None
  pidfile: None
  worker_tmp_dir: None
  group: 1000
  graceful_timeout: 30
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7f595f8485f0>
  post_worker_init: <function post_worker_init at 0x7f595f848b90>
  pre_exec: <function pre_exec at 0x7f595f84c050>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f595f84c6e0>
  config: None
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f595f84c1b8>
  post_request: <function post_request at 0x7f595f84c2a8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f595f848cf8>
  ca_certs: None
  threads: 1
  max_requests: 0
  chdir: /home/ank/projects/tweety-app/tweety
  daemon: False
  user: 1000
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f595f84c410>
  paste: None
  default_proc_name: tweety.wsgi:application
  errorlog: ./gunicorn_tweety.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7f595f848e60>
  loglevel: debug
  bind: ['0.0.0.0:5000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f595f84c578>
  timeout: 30
  on_starting: <function on_starting at 0x7f595f848488>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
2017-07-08 21:50:32 [28161] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:50:32 [28161] [DEBUG] Arbiter booted
2017-07-08 21:50:32 [28161] [INFO] Listening at: http://0.0.0.0:5000 (28161)
2017-07-08 21:50:32 [28161] [INFO] Using worker: sync
2017-07-08 21:50:32 [28167] [INFO] Booting worker with pid: 28167
2017-07-08 21:50:32 [28161] [INFO] 1 workers
2017-07-08 21:50:32 [28167] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2017-07-08 21:50:32 [28167] [INFO] Worker exiting (pid: 28167)
2017-07-08 21:50:32 [28161] [INFO] Shutting down: Master
2017-07-08 21:50:32 [28161] [INFO] Reason: Worker failed to boot.
2017-07-08 21:50:48 [28222] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:50:48 [28222] [INFO] Listening at: http://0.0.0.0:5000 (28222)
2017-07-08 21:50:48 [28222] [INFO] Using worker: sync
2017-07-08 21:50:48 [28228] [INFO] Booting worker with pid: 28228
2017-07-08 21:50:48 [28222] [INFO] 1 workers
2017-07-08 21:50:49 [28228] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2017-07-08 21:50:49 [28228] [INFO] Worker exiting (pid: 28228)
2017-07-08 21:50:49 [28222] [INFO] Shutting down: Master
2017-07-08 21:50:49 [28222] [INFO] Reason: Worker failed to boot.
2017-07-08 21:54:46 [28793] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  syslog: False
  statsd_host: ('localhost', 8125)
  post_fork: <function post_fork at 0x7fc980caf9b0>
  pythonpath: ./tweety
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7fc980caf6e0>
  pre_fork: <function pre_fork at 0x7fc980caf848>
  cert_reqs: 0
  preload_app: False
  workers: 1
  keepalive: 2
  accesslog: None
  pidfile: None
  worker_tmp_dir: None
  group: 1000
  graceful_timeout: 30
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7fc980caf578>
  post_worker_init: <function post_worker_init at 0x7fc980cafb18>
  pre_exec: <function pre_exec at 0x7fc980caff50>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fc980cb4668>
  config: None
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fc980cb4140>
  post_request: <function post_request at 0x7fc980cb4230>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fc980cafc80>
  ca_certs: None
  threads: 1
  max_requests: 0
  chdir: /home/ank/projects/tweety-app/tweety
  daemon: False
  user: 1000
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fc980cb4398>
  paste: None
  default_proc_name: tweety.wsgi:application
  errorlog: ./gunicorn_tweety.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7fc980cafde8>
  loglevel: debug
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fc980cb4500>
  timeout: 30
  on_starting: <function on_starting at 0x7fc980caf410>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
2017-07-08 21:54:46 [28793] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:54:46 [28793] [DEBUG] Arbiter booted
2017-07-08 21:54:46 [28793] [INFO] Listening at: http://127.0.0.1:8000 (28793)
2017-07-08 21:54:46 [28793] [INFO] Using worker: sync
2017-07-08 21:54:46 [28798] [INFO] Booting worker with pid: 28798
2017-07-08 21:54:46 [28793] [INFO] 1 workers
2017-07-08 21:54:47 [28798] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/home/ank/projects/tweety-app/tweety/tweety/wsgi.py", line 7, in <module>
    from dj_static import Cling # define this after setting the DJANGO_SETTINGS_MODULE environment variable
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/dj_static.py", line 7, in <module>
    from django.contrib.staticfiles.handlers import StaticFilesHandler as DebugHandler
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py", line 13, in <module>
    from django.views import static
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/views/static.py", line 96, in <module>
    template_translatable = ugettext_noop("Index of %(directory)s")
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 65, in gettext_noop
    return _trans.gettext_noop(message)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/django/conf/__init__.py", line 151, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2017-07-08 21:54:47 [28798] [INFO] Worker exiting (pid: 28798)
2017-07-08 21:54:47 [28793] [INFO] Shutting down: Master
2017-07-08 21:54:47 [28793] [INFO] Reason: Worker failed to boot.
2017-07-08 21:55:15 [28915] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  syslog: False
  statsd_host: ('localhost', 8125)
  post_fork: <function post_fork at 0x7f4b397969b0>
  pythonpath: ./tweety
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7f4b397966e0>
  pre_fork: <function pre_fork at 0x7f4b39796848>
  cert_reqs: 0
  preload_app: False
  workers: 1
  keepalive: 2
  accesslog: None
  pidfile: None
  worker_tmp_dir: None
  group: 1000
  graceful_timeout: 30
  spew: False
  proc_name: None
  umask: 0
  on_reload: <function on_reload at 0x7f4b39796578>
  post_worker_init: <function post_worker_init at 0x7f4b39796b18>
  pre_exec: <function pre_exec at 0x7f4b39796f50>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f4b3979b668>
  config: None
  logconfig: None
  check_config: False
  do_handshake_on_connect: False
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f4b3979b140>
  post_request: <function post_request at 0x7f4b3979b230>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f4b39796c80>
  ca_certs: None
  threads: 1
  max_requests: 0
  chdir: /home/ank/projects/tweety-app/tweety
  daemon: False
  user: 1000
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f4b3979b398>
  paste: None
  default_proc_name: tweety:application
  errorlog: ./gunicorn_tweety.log
  logger_class: gunicorn.glogging.Logger
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x7f4b39796de8>
  loglevel: debug
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f4b3979b500>
  timeout: 30
  on_starting: <function on_starting at 0x7f4b39796410>
  debug: False
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
2017-07-08 21:55:15 [28915] [INFO] Starting gunicorn 19.1.0
2017-07-08 21:55:15 [28915] [DEBUG] Arbiter booted
2017-07-08 21:55:15 [28915] [INFO] Listening at: http://127.0.0.1:8000 (28915)
2017-07-08 21:55:15 [28915] [INFO] Using worker: sync
2017-07-08 21:55:15 [28920] [INFO] Booting worker with pid: 28920
2017-07-08 21:55:15 [28920] [DEBUG] Exception while loading the application: 
Traceback (most recent call last):
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ank/projects/tweety-app/local/lib/python2.7/site-packages/gunicorn/util.py", line 369, in import_app
    raise AppImportError("Failed to find application: %r" % module)
AppImportError: Failed to find application: 'tweety'

2017-07-08 21:55:15 [28920] [INFO] Worker exiting (pid: 28920)
